format = """\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $package\
  $golang\
  $ruby\
  $python\
  $line_break\
  $character\
"""

[cmd_duration]
show_milliseconds = true
style = "bold grey"
min_time = 1_000

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](green)"

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 2
style = "blue"

[git_branch]
symbol = "ğŸŒ± "

[golang]
symbol = "ğŸ¦¦"

[python]
style = "yellow"

[time]
disabled = true

scan_timeout = 10 # wait to scan files in dir
