format = """\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $package\
  $golang\
  $ruby\
  $python\
  $cmd_duration\
  $line_break\
  $character\
"""

[cmd_duration]
show_milliseconds = true
style = "bold grey"
min_time = 1_000

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 2

[git_branch]
symbol = "ğŸŒ±"

[golang]
symbol = "ğŸ¦¦"

[python]
symbol = "ğŸ"

[time]
disabled = false
format = "[%T]"
style = "dimmed black"

